import {
    faCircleQuestion,
    faComment,
    faUser,
    faMagnifyingGlass,
    faLocationDot,
    faBook,
    faChalkboardTeacher,
    faGlobe,
    faLocation,
    faLanguage,
    faMale,
    faQuestion,
    faDollarSign,
    faGraduationCap,
    faAngleRight,
    faAngleLeft,
    faX,
} from "@fortawesome/free-solid-svg-icons";

export default function getIcons() {
    return {
        faCircleQuestion,
        faComment,
        faUser,
        faMagnifyingGlass,
        faLocationDot,
        faBook,
        faChalkboardTeacher,
        faGlobe,
        faLocation,
        faLanguage,
        faMale,
        faQuestion,
        faDollarSign,
        faGraduationCap,
        faAngleRight,
        faAngleLeft,
        faX,
    };
}
